# Generated by Django 6.0.2 on 2026-02-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('rabies', 'Бешенство'), ('distemper', 'Чумка'), ('parvovirus', 'Парвовирус'), ('leptospirosis', 'Лептоспироз'), ('kennel_cough', 'Питомниковый кашель'), ('feline_leukaemia', 'Вирусный лейкоз кошек'), ('other', 'Другая')], max_length=50, verbose_name='Тип вакцины')),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='Название вакцины')),
                ('administration_date', models.DateField(verbose_name='Дата введения')),
                ('next_vaccination_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей вакцинации')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Номер партии')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient', verbose_name='Пациент')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.veterinarian', verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
                'ordering': ['-administration_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('examination', 'Осмотр'), ('vaccination', 'Вакцинация'), ('surgery', 'Операция'), ('test', 'Анализ/Тест'), ('treatment', 'Лечение'), ('diagnostic', 'Диагностика'), ('prescription', 'Назначение'), ('other', 'Другое')], default='examination', max_length=20, verbose_name='Тип записи')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
                ('treatment', models.TextField(blank=True, verbose_name='Лечение/Назначения')),
                ('prescription', models.TextField(blank=True, verbose_name='Рецепт')),
                ('record_date', models.DateTimeField(verbose_name='Дата записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура (°C)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Пульс (уд/мин)')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment', verbose_name='Запись на прием')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Пациент')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.veterinarian', verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['patient', 'record_date'], name='medical_car_patient_7486dc_idx'), models.Index(fields=['record_type'], name='medical_car_record__33ca5d_idx')],
            },
        ),
    ]
