# Generated by Django 6.0.2 on 2026-02-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(choices=[('general', 'Общая практика'), ('surgeon', 'Хирург'), ('dentist', 'Стоматолог'), ('dermatologist', 'Дерматолог'), ('ophthalmologist', 'Офтальмолог'), ('cardiologist', 'Кардиолог')], default='general', max_length=50, verbose_name='Специализация')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Стаж (лет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Ветеринар',
                'verbose_name_plural': 'Ветеринары',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('reason', models.TextField(blank=True, verbose_name='Причина обращения')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Назначенное лечение')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('confirmed', 'Подтвержден'), ('in_progress', 'На приеме'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('no_show', 'Не явился')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Пациент')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.veterinarian', verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_fb412a_idx'), models.Index(fields=['patient', 'veterinarian'], name='appointment_patient_1621c3_idx')],
            },
        ),
    ]
