# Generated by Django 6.0.2 on 2026-02-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка животного')),
                ('animal_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('rabbit', 'Кролик'), ('other', 'Другое')], max_length=20, verbose_name='Вид животного')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('age', models.IntegerField(verbose_name='Возвраст')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Телефон владельца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
